// <auto-generated />
using System;
using ARMTIS_Capstone_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARMTIS_Capstone_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818025639_AddUtilityRateTable")]
    partial class AddUtilityRateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.Main.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("TenantID");

                    b.HasIndex("UnitID");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.Main.Unit", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitID");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.BillingStatement", b =>
                {
                    b.Property<int>("BillingStatementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingStatementID"));

                    b.Property<DateTime>("BillingMonth")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillingNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Electricity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Internet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.Property<decimal>("UtilityCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillingStatementID");

                    b.HasIndex("TenantID");

                    b.HasIndex("UnitID");

                    b.ToTable("BillingStatements");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.RentalPayment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingMonth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BillingStatementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("BillingStatementID");

                    b.HasIndex("TenantID");

                    b.ToTable("RentalPayments");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.UtilityRate", b =>
                {
                    b.Property<int>("UtilityRateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityRateID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UtilityRateID");

                    b.ToTable("UtilityRates");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.UtilityReading", b =>
                {
                    b.Property<int>("UtilityReadingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityReadingID"));

                    b.Property<DateTime>("BillingMonth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentWaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ElectricConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricityBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InternetBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousElectricReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousWaterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalUtilityCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.Property<decimal>("WaterBill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UtilityReadingID");

                    b.HasIndex("UnitID");

                    b.HasIndex("TenantID", "BillingMonth")
                        .IsUnique();

                    b.ToTable("UtilityReadings");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.Main.Tenant", b =>
                {
                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Unit", "Unit")
                        .WithMany("Tenants")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.BillingStatement", b =>
                {
                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.RentalPayment", b =>
                {
                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.BillingStatement", "BillingStatement")
                        .WithMany()
                        .HasForeignKey("BillingStatementID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingStatement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.PaymentModels.UtilityReading", b =>
                {
                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ARMTIS_Capstone_Project.MVVM.Models.Main.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ARMTIS_Capstone_Project.MVVM.Models.Main.Unit", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
